server:
  port: 8080

logging:
  level:
    root: warn
    edu:
      nju:
        codefeature: info
        codefeature.tools: info

pythonPath: /usr/bin/python3.6
#  pythonPath: /usr/bin/python3

fileConfig:
  trainDataPath: /home/qian/Desktop/CWE15/test/data
  modelPath: /home/qian/Desktop/CWE15/test/model
  tempPath: /home/qian/Desktop/CWE15/test/temp

testConfig:
  dataPath: /home/qian/Desktop/CWE15/test
  outputPath: /home/qian/Desktop/CWE15/test/output
  modelPath: /home/qian/Desktop/CWE15/test/model
#  modelPath: /root/version2/model
#  dataPath: /root/version1/
#  outputPath: /root/version2/output/
  featureSize: 16
  epochNum: 10
